### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by rwdj** [ErdbeerbaerLP/DiscordIntegration-Addon-Repository#1]
26.07 19:27:17 [Server] main/WARN [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file Mod File: /mods/DiscordIntegration-VoiceNotifications-1.0.0.jar is missing mods.toml file
26.07 19:27:17 [Server] main/WARN [ne.mi.fm.lo.mo.ModDiscoverer/SCAN]: File /mods/DiscordIntegration-VoiceNotifications-1.0.0.jar has been ignored - it is invalid

The current release 1.0.0 from https://github.com/ErdbeerbaerLP/DiscordIntegration-Voice-Notifications/releases/tag/1.0.0 shows this in META_INF:

$ cd META-INF
$ ls
`MANIFEST.MF`
$ cat MANIFEST.MF
`Manifest-Version: 1.0`

Using 1.16.5.
DiscordIntegration 2.0.0
Forge 36.1.32

**Comment by ErdbeerbaerLP** [comment]
This is not an mod, it has to be put into `SERVER/DiscordIntegration-Data/addons` to load

**Comment by rwdj** [comment]
Ah. I see. Thank you!
