### ISSUE TITLE
Not available on CurseForge

### ISSUE THREAD

**Issue by rwdj** [ErdbeerbaerLP/DiscordIntegration-Addon-Repository#2]
https://www.curseforge.com/minecraft/mc-mods/search?search=discord+voice
https://www.curseforge.com/minecraft/mc-mods/search?search=discordintegration+voice

**Comment by ErdbeerbaerLP** [comment]
This is not an mod, but an addon for the mod. So this won't be released to curseforge

**Comment by rwdj** [comment]
Ah. I see. #1. Thank you!
